import type { Metadata } from "next";
import { Providers } from "./Providers";
import { Navbar } from "@/packages/ui-patterns/navigation";
import { Footer } from "@/packages/ui-patterns/navigation/Footer";
import { Box } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar h="8vh"/>
          <Box h="calc(100vh - 16vh)">
            <main>{children}</main> 
          </Box>
          <Footer display={{ base: "none", md: "flex" }} h="8vh"/>
        </Providers>
      </body>
    </html>
  );
}
